- junitparser/junitparser.py
- setup.py
- test.py
Encode htmlentities when fetching attribute values.
A solution to #27
> ensure htmlentities are used in attributes

- junitparser/junitparser.py
Commit 6db59f3cc3c4f421c5b0ccdd72d4915a0fa503ef added a call to
update_statistics() to add_testcase(). When merging files, add_testcase()
is called many times and every call to update_statistics will walk the
entire XML tree again. There is no need to do this on every add_testcase().
Instead update the statistics once after the file has been merged.
When merging large JUnit XML files, this reduces the merge time from
many minutes to less than one second.
> Major speedup to merging of files

- junitparser/junitparser.py
My test function in question returns either `Failure()`, `Error()`, `Skipped()` or `None`. Where `None` indicates a 'pass'. The result of my test function is directly fed into `testcase.result`. 
With the current implementation in junitparser this raises an error: `AttributeError: 'NoneType' object has no attribute '_elem'`. In short, returning anything else than `Failure()`, `Error()` or `Skipped()` results in a similar error. Since before appending the current result, the type is not checked. 
For robustness I suggest adding the the `isinstance()` check before appending the current result.
> Adding isinstance() check before appending result

- junitparser/junitparser.py
In an earlier PR I proposed to add the `isinstance()` check before appending the test result. In fact, the value is now being checked against the wrong instance. So, the result will never be appended since `value` is not an instance of `System`. 
Solution: `value` should be an instance of `Skipped`, `Failure` or `Error`.
> Changed isinstance() check to Skipped, Failure and Error types

- junitparser/junitparser.py
Before this change it was only available after calling update_statistics().
> Add skipped member to JUnitXml

- junitparser/cli.py
- junitparser/junitparser.py
- test.py
Fix #47 
Additionally, if two files contains the same suite, after adding, instead of creating two suites of the same name, the tests will be merged into one suite.
> fix: #47 merge gives wrong result

- CHANGELOG.md
- README.rst
- junitparser/__init__.py
- junitparser/junitparser.py
- tests/test_fromfile.py
- tests/test_general.py
> fix: multiple results won't crash the parser

- .github/workflows/build.yml
- junitparser/junitparser.py
- tests/test_general.py
Currently junitparser will fail on junit report containing long test (over 1000 seconds) with time attribute set to localized float representation, which may include commas - e.g. 1,200.058. I'm attempting to fix it by:
- setting locale from environment variables
- using locale.atof(result) instead of float(result)
In tests I'm setting locale manually to 'en_US.UTF-8'. Since there's no guarantee that any specific locale exists on system,
I'm failing to testing without comma included in such case.
> fix parsing localized float strings

- .github/workflows/build.yml
- junitparser/junitparser.py
- tests/test_general.py
Assumes JUnit XML files always contain numbers formatted in C locale, optionally with thousands separator, as reported in #58. This simplifies #58 which broke junitparser when running in environments with locales that are incompatible with C or en_US (for instance de_DE). For more details, see #64.
This implementation mimics the behaviour of `atof` given a C locale (which in that situation only removes the thousands separator `,` and parses the result with `float()`).
Adds tests that C locale formatted time string is identically parsed in `en_US` and `de_DE` locals.
> Remove locale sensitivity when parsing numbers, simplifies #58

- junitparser/junitparser.py
- tests/data/jenkins.xml
- tests/test_fromfile.py
According to https://llg.cubic.org/docs/junit/, `<testsuite>` can be child of `<testsuite>`. This fix allows to iterate over all TestCase leafs under a TestSuite.
I am not sure which implications this "feature" has on merging and writing xml files, as I have never used that.
> Support testcase tags inside testcase tags

- junitparser/junitparser.py
Occasionally accumulation of the time fields for testcase and testsuite elements (especially if there are several small duration tests) will result in time representation being printed with invalid precision (e.g. 0.4420000000000001)
There does not seem to be a source of truth for schema validation but the xunit-plugin for jenkins does provide this one https://github.com/jenkinsci/xunit-plugin/blob/master/src/main/resources/org/jenkinsci/plugins/xunit/types/model/xsd/junit-10.xsd
According to the above limiting precision to 3 places seems proper)
> Fix representation of time precision

- junitparser/junitparser.py
Using generators improves speed and reduces memory consumption.
> Remove unnecessary list comprehensions

- junitparser/cli.py
https://github.com/weiwei/junitparser/commit/ae78dd61a1389924d51d33def488cb112f3f5f47 was good but broke the merge command in cli.py.
This fixes that. #78
> Fix typo in cli merge

- junitparser/junitparser.py
- tests/test_general.py
This allows to create an `JUnitXML` instance from an `ElementTree` root element, just like parsing a file.
Use case: I have parsed a file into an `ElementTree` and performed some operations on that tree. From the final tree, I want to create the `JUnitXML` object, identical to `JUnitXML.fromfile` and `JUnitXML.fromstring`.
There is some extra logic in `JUnitXML.fromfile` and `JUnitXML.fromstring`, that is not in `Element.fromelem`.
> Add JUnitXML.fromroot

- junitparser/junitparser.py
- tests/test_general.py
The iteration in TestCase.result.setter did not work properly when using xml.etree instead of lxml.etree. This was because the Element.remove() method was being invoked while iterating the elements, and apparently xml.etree does not support that.
Instead, use a prepopulated lits of Elements to iterate and remove.
Fixes #99.
Signed-off-by: Carles Cufi <carles.cufi@nordicsemi.no>
> junitparser.py: Fix removing items with xml.etree

- tests/test_cli.py
- tests/test_fromfile.py
- tests/test_general.py
- tests/test_xunit2.py
The command line conversion tools didn't work, but Copilot works quite good for converting individual cases. Probably the only good case to justify me buying it. Still a lot of manual copy/paste though.
Some cases are rewritten to use `parametrize`.
> Convert to pytest

- .readthedocs.yml
- docs/requirements.txt
See https://docs.readthedocs.io/en/stable/config-file/v2.html
Without this, the builds are failing, see e.g. https://readthedocs.org/projects/junitparser/builds/21963453/
> Add files now needed for the ReadTheDocs run

- .readthedocs.yml
> Fix path for RTD sphinx-apidoc pre_build step

- .github/workflows/build.yml
- junitparser/junitparser.py
Some more type annotations.
Note to self: the `Self` type is only supported with python 3.11, and the official backport only works for 3.8+, while this package still has quite a few users on Python 3.6 and 3.7, so it is not added.
> some more type annotations

- junitparser/junitparser.py
`pytest` gives a warning on `TestCase` and `TestSuite` during test discovery. 
Adding `__test__ = False` to each class excludes from test discovery and removes warning.
> Exclude TestCase and TestSuite from pytest discovery

- junitparser/junitparser.py
- junitparser/xunit2.py
- tests/test_xunit2.py
Currently, `junitparser.xunit2.JUnitXml.fromroot` returns a `junitparser.JUnitXml.TestSuite`, but you would expect a `junitparser.xunit2.TestSuite`, which implements XUnit2-specific features.
> Calling `junitparser.xunit2.JUnitXml.fromroot` should produce `junitparser.xunit2.TestSuite`

- junitparser/junitparser.py
- tests/test_general.py
> fix #133 typing

- junitparser/junitparser.py
- junitparser/xunit2.py
Previously `for suite in xml` and `for case in suite` would not detect the proper types for `suite` and `case` and not give intelisense.
this fixes the elements being detected as type `Any` and instead the proper type is detected, enableing auto-completeion.
> Type-hinting for looping over the xml children

- junitparser/junitparser.py
- junitparser/xunit2.py
- tests/test_xunit2.py
Iterating over a `xuni2.JUnitXml` should return `xunit2.TestSuite` and `xunit2.TestCase` instances, not the default implementations `junitparser.TestSuite` and `junitparser.TestCase`. Follow-up of #134.
> Fix type of suites and cases returned when iterating xunit2.JUnitXml

- CHANGELOG.md
- README.rst
- junitparser/junitparser.py
- junitparser/xunit2.py
- tests/test_xunit2.py
Improves class hierarchy and naming of results returned by `JUnitXml.TestCase.result`, in contrast to rerun results defined in `xunit2`.
Note: This is a breaking change. Before, `TestCase.result` silently ignored values that were not of type `Result`. This setter method now raises a `ValueError` if values are not of type `FinalResult`.
> Distinguishing between JUnit final results and XUnit2 interim (rerun & flaky) results

- CHANGELOG.md
- junitparser/cli.py
- junitparser/junitparser.py
- tests/test_fromfile.py
- tests/test_write.py
Method `fromfile` already supports reading file objects, file-like objects and urls. This is now tested and documented.
Similarly, methods `write_xml` and `write` now support writing to file objects and file-like objects. This makes `to_console` argument redundant.
Asserts the actual written XML content.
> Write to file and file-like objects

- junitparser/junitparser.py
- junitparser/xunit2.py
- tests/test_general.py
- tests/test_xunit2.py
Adds more test state helper methods like `is_failure`, `is_error`, `is_rerun` and `is_flaky`. Further, provides easier access to all interim result types (iterating over `TestCase` or calling `interim_result` property).
> More test result methods

- junitparser/junitparser.py
- junitparser/xunit2.py
- tests/test_xunit2.py
Follow up on #143, now it should be possible to properly derive all 3 classes (JUnitXml, TestSuite, TestCase) without loosing information while e.g. adding 2 testsuites to each other.
> Enable inheritance

- .github/workflows/ci.yml
Ubuntu 20.04 will be sunset by <strike>2024-04-01</strike> 2024-04-15.
With this, we lose test coverage for Python 3.6 an 3.7.
https://github.com/actions/runner-images/issues/11101
> Remove Ubuntu 20.04 from CI
